# .github/workflows/gitlab-mirror.yml
name: GitLab Mirror (reusable)

on:
  workflow_call:
    inputs:
      gitlab_url:
        description: "Target GitLab repo HTTPS URL (ends with .git)"
        required: true
        type: string
    secrets:
      gitlab_token:
        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: gitlab-mirror-${{ github.repository }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Push branches & tags (non-destructive)
        env:
          GITLAB_URL: ${{ inputs.gitlab_url }}
          GITLAB_TOKEN: ${{ secrets.gitlab_token }}
        run: |
          set -euo pipefail
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL#https://}"
          git push gitlab --force-with-lease --all
          git push gitlab --force-with-lease --tags
